name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          VERSION_PREFIX="V1.0.0_"  # Assuming the initial version format
          
          # Find the latest tag if available
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "")
          
          if [ -z "$LATEST_TAG" ]; then
            # If no tags found, start with patch version 0 and branch name
            NEW_TAG="${VERSION_PREFIX}${GITHUB_REF#refs/heads/}"
          else
            # Extract the patch version and branch name from the latest tag
            PATCH_BRANCH=$(echo "$LATEST_TAG" | cut -d'_' -f2)
            PATCH_VERSION=$(echo "$PATCH_BRANCH" | grep -oE '[0-9]+$')
            BRANCH_NAME=$(echo "$PATCH_BRANCH" | sed 's/[0-9]*$//')
            # Increment the patch version
            PATCH_VERSION=$((PATCH_VERSION + 1))
            # Construct the new tag
            NEW_TAG="${VERSION_PREFIX}${BRANCH_NAME}${PATCH_VERSION}"
          fi
          
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git config user.name "Nithish@NetXD"
          git config user.email "nithish.t@netxd.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
