name: Version Incrementation

on:
  push:
    branches:
      - main

jobs:
  increment_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Tag
        id: latest_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0_QA")
          echo "latest_tag=${latest_tag}" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          major=$(echo "${latest_tag}" | cut -d'.' -f1 | sed 's/v//')
          minor=$(echo "${latest_tag}" | cut -d'.' -f2)
          patch=$(echo "${latest_tag}" | cut -d'.' -f3 | cut -d'_' -f1)
          minor=$((minor + 1))
          new_version="v${major}.${minor}.${patch}_QA"
          echo "new_version=${new_version}" >> $GITHUB_ENV

      - name: Set up Git
        run: |
          git config --global user.email "nithish.t@netxd.com"
          git config --global user.name "Nithish@NetXD"

      - name: Create and Push Tag
        run: |
          git tag "${new_version}"
          git push origin "${new_version}" --force
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
